# Generated by Django 3.0.4 on 2020-05-19 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_auto_20200427_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(blank=True)),
                ('title', models.CharField(default='Untitled', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_note_creator', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='shared_note_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
